### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by patrickmineault** [ahwillia/netrep#10]
There's a `requirements.txt` file inside the package which is not necessary. In reality, I believe you only need numpy, scipy, sklearn and tqdm to run this, based off of running the tests. You could fix this by removing `requirements.txt` and changing `setup.py` like to:

```python
import setuptools

setuptools.setup(
    name="netrep",
    version="0.0.2",
    url="https://github.com/ahwillia/netrep",

    author="Alex Williams",
    author_email="ahwillia@stanford.edu",

    description="Simple methods for comparing network representations.",

    packages=setuptools.find_packages(),
    install_requires=[
        'numpy>=1.16.5',
        'scipy>=1.3.1',
        'scikit-learn>=0.21.3',
        'tqdm>=4.32.2'
    ],
    extras_require={
        'dev': [
            'pytest>=3.7'
        ]
    },
)
```

**Comment by ahwillia** [comment]
Thanks, this is done. If there is demand we can flesh out a more proper and stable package with CI.
