### ISSUE TITLE
Possible error in euclidean metric?

### ISSUE THREAD

**Issue by wrongu** [ahwillia/netrep#3]
I'm looking at this line which defines the Euclidean distance: https://github.com/ahwillia/netrep/blob/main/netrep/metrics/linear.py#L150

From your paper and the Dryden book, I understood the size-and-shape distance to be calculated using the Frobenius norm, which would be proportional to the root-mean-squared of `np.linalg.norm(..., axis=1)` rather than its mean as you've implemented it. (Or, simply `np.linalg.norm(..., ord='fro')`)

Did I misunderstand something here, or is this an error?

**Comment by ahwillia** [comment]
Good catch, I think what I have there originally could be made to work (see Appendix D), but it would be best to be consistent with the book/paper. I was trying to be to clever by making the metric here invariant to `m` the number of images. 

Fixed here: https://github.com/ahwillia/netrep/commit/3059f54230e85931fe4d10709b41185f0310a21a

**Comment by wrongu** [comment]
Quick work! I see the appeal of a metric that converges for large m instead of growing. Dividing the Frobenius norm by √m might also do the trick? But yes I think it's nicer in this context to have the euclidean and angular metrics consistent in the sense that the euclidean metric provides the ambient metric for the sphere of unit-frobenius-norm, and the angular metric provides the arc length on that sphere.

**Comment by ahwillia** [comment]
Yes. Someday I may find time to clean up this package and make all of these options more transparent. Thanks for your interest!
