### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PeerHerholz** [ahwillia/netrep#8]
Hi everyone,

thank you very much for this amazing resource!

I was wondering if you were planning to add a `license` to the `repro` soon(-ish), outlining
respective usage rights?

Thanks again. Cheers,  Peer

**Comment by ahwillia** [comment]
Sorry for the oversight and thanks for bringing this to our attention. I just attached an MIT license: https://github.com/ahwillia/netrep/pull/9
